// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9wW71FmMfBANxhBYIy8HLQKEYRYO47PM',
    appId: '1:597073806092:web:67fcaf2c331be88ebc3f29',
    messagingSenderId: '597073806092',
    projectId: 'registration-47c93',
    authDomain: 'registration-47c93.firebaseapp.com',
    storageBucket: 'registration-47c93.firebasestorage.app',
    measurementId: 'G-LK3Q2B2KZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs9VeHXSvf4Tmh7n0b18S_k8sErtM_O4U',
    appId: '1:597073806092:android:8ba254011c652872bc3f29',
    messagingSenderId: '597073806092',
    projectId: 'registration-47c93',
    storageBucket: 'registration-47c93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtYp16gj1etaLDZ9ldU88GWtRNKlx01-g',
    appId: '1:597073806092:ios:539c366b97a36f06bc3f29',
    messagingSenderId: '597073806092',
    projectId: 'registration-47c93',
    storageBucket: 'registration-47c93.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtYp16gj1etaLDZ9ldU88GWtRNKlx01-g',
    appId: '1:597073806092:ios:539c366b97a36f06bc3f29',
    messagingSenderId: '597073806092',
    projectId: 'registration-47c93',
    storageBucket: 'registration-47c93.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9wW71FmMfBANxhBYIy8HLQKEYRYO47PM',
    appId: '1:597073806092:web:d6dfd1c59e6dec66bc3f29',
    messagingSenderId: '597073806092',
    projectId: 'registration-47c93',
    authDomain: 'registration-47c93.firebaseapp.com',
    storageBucket: 'registration-47c93.firebasestorage.app',
    measurementId: 'G-9CX523S83X',
  );
}
